#!/bin/bash

assert_equal() {
    local expected="$1"
    local actual="$2"
    [[ "$actual" == "$expected" ]] && {
    echo "$(tput setaf 2)PASS$(tput sgr0)"
    } || {
        echo "Expected: $expected"
        echo "  Actual: $actual"
    }
}

assert_equal "" "$(bin/add)"
assert_equal "1" "$(bin/add "1")"
assert_equal "\
Expected: 1
  Actual: 2" "$(assert_equal 1 2)"

assert_equal "3" "$(bin/add "3")"
assert_equal "3" "$(bin/add "1,2")"
assert_equal "6" "$(bin/add "1,2,3")"
